name = "qq-music-player"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "qqmusic-credentials"
database_id = "78640b14-91d6-4090-a7d1-9568dcf2f0ff"

# 定时刷新凭证 (每小时)
[triggers]
crons = ["0 * * * *"]

# 初始凭证配置
[vars]
EXTERNAL_API_URL = "https://api.ygking.top"
